import { spawn } from "node:child_process";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { parseAgentResult } from "@ticket-to-pr/core";
import { getWorkspacePaths, parseRunnerContext } from "@ticket-to-pr/runner-contract";

export interface E2eSmokeRunnerInput {
  workspaceRoot: string;
  repoDir: string;
  targetBranch: string;
}

export async function runE2eSmokeRunner(input: E2eSmokeRunnerInput): Promise<void> {
  const paths = getWorkspacePaths(input.workspaceRoot);
  const context = parseRunnerContext(await readFile(paths.contextJson, "utf8"));
  const baseSha = (await runGit(["rev-parse", "HEAD"], input.repoDir)).stdout.trim();

  await runGit(["config", "user.name", "Ticket-to-PR Bot"], input.repoDir);
  await runGit(["config", "user.email", "ticket-to-pr@example.local"], input.repoDir);
  await appendSmokeNote(input.repoDir, context.jobId);
  await runGit(["add", "README.md"], input.repoDir);
  await runGit(["commit", "-m", "docs: add Lark automation smoke note"], input.repoDir);

  const headSha = (await runGit(["rev-parse", "HEAD"], input.repoDir)).stdout.trim();
  const changedFiles = (await runGit(["diff", "--name-only", `${baseSha}...${headSha}`], input.repoDir)).stdout
    .split("\n")
    .map((line) => line.trim())
    .filter(Boolean);
  const commitMessage = (await runGit(["log", "-1", "--format=%s"], input.repoDir)).stdout.trim();

  await mkdir(paths.outputDir, { recursive: true });
  await writeFile(paths.prTitle, "docs: add Lark automation smoke note\n");
  await writeFile(
    paths.prBody,
    [
      "## Summary",
      "- Add a concise README note generated by the Lark Base automation smoke path.",
      "",
      "## Verification",
      "- README.md only",
      "- E2E compatible runner completed",
    ].join("\n"),
  );
  await writeFile(
    paths.resultJson,
    `${JSON.stringify(
      parseAgentResult({
        schemaVersion: "1.0",
        runId: context.runId,
        jobId: context.jobId,
        ticketId: context.ticketSnapshotId,
        triggerVersion: context.triggerVersion,
        status: "completed",
        targetBranch: input.targetBranch,
        baseSha,
        headSha,
        pushSha: headSha,
        changedFiles,
        commits: [{ sha: headSha, message: commitMessage }],
        tests: [
          {
            command: "git diff --name-only",
            status: "passed",
            summary: changedFiles.join(", ") || "No changed files",
          },
        ],
        review: {
          summary: "README-only Lark automation smoke change generated for Ticket-to-PR E2E validation.",
          risks: [],
          knownLimitations: ["This runner is a deterministic E2E smoke runner, not an AI code implementation agent."],
        },
        pullRequestDraft: {
          title: "docs: add Lark automation smoke note",
          bodyPath: "output/pr-body.md",
        },
        failure: null,
        retryable: false,
      }),
      null,
      2,
    )}\n`,
  );
}

async function appendSmokeNote(repoDir: string, jobId: string): Promise<void> {
  const readmePath = path.join(repoDir, "README.md");
  let readme = "";
  try {
    readme = await readFile(readmePath, "utf8");
  } catch {
    readme = "# Repository\n";
  }

  const note = [
    "",
    "## Lark automation smoke test",
    "",
    `Ticket-to-PR created this README-only smoke change from Lark Base job ${jobId}.`,
    "",
  ].join("\n");
  await writeFile(readmePath, `${readme.trimEnd()}${note}`);
}

function runGit(args: string[], cwd: string): Promise<{ stdout: string; stderr: string }> {
  return new Promise((resolve, reject) => {
    const child = spawn("git", args, { cwd, stdio: ["ignore", "pipe", "pipe"] });
    const stdoutChunks: Buffer[] = [];
    const stderrChunks: Buffer[] = [];
    child.stdout.on("data", (chunk: Buffer) => stdoutChunks.push(chunk));
    child.stderr.on("data", (chunk: Buffer) => stderrChunks.push(chunk));
    child.on("error", reject);
    child.on("close", (code) => {
      const stdout = Buffer.concat(stdoutChunks).toString("utf8");
      const stderr = Buffer.concat(stderrChunks).toString("utf8");
      if (code === 0) {
        resolve({ stdout, stderr });
        return;
      }
      reject(new Error(`git ${args.join(" ")} failed with code ${code ?? "unknown"}: ${stderr || stdout}`));
    });
  });
}

const mainPath = process.argv[1] ? path.resolve(process.argv[1]) : undefined;
if (mainPath === fileURLToPath(import.meta.url)) {
  const workspaceRoot = process.env.WORKSPACE_ROOT;
  const targetBranch = process.env.TARGET_BRANCH;
  if (!workspaceRoot || !targetBranch) {
    console.error("WORKSPACE_ROOT and TARGET_BRANCH are required");
    process.exitCode = 1;
  } else {
    runE2eSmokeRunner({
      workspaceRoot,
      repoDir: getWorkspacePaths(workspaceRoot).repoDir,
      targetBranch,
    }).catch((error: unknown) => {
      console.error(error instanceof Error ? error.message : String(error));
      process.exitCode = 1;
    });
  }
}
